Fixed some indenting, changed getPortalias() to return the value. Tested.

diff --git a/paradigm b/paradigm
--- a/paradigm
+++ b/paradigm
@@ -15,15 +15,15 @@
 
 #==========# THIS IS AT THE TOP FOR YOU TO READ FIRST #==========#
 showHelp() {
-    cat << EOF
+  cat << EOF
 Usage: [OPTION] PLAYNODE SERVICENAME SERVICEPORT SERVER
 
 -h, ?
-    Print this usage text.
+  Print this usage text.
 -u 
-    User account on server. Default=paradigm
+  User account on server. Default=paradigm
 -P 
-    SERVERLISTENINGPORT default=22
+  SERVERLISTENINGPORT default=22
 
 A playnode is a name to define a group of service ports, usually the hostname.
 User account on remote server with shell access required.
@@ -33,8 +33,8 @@ Where dummy is the playnode name, and 32767 is the server local port
 A server-side script registers new playnodes to new ports in this file.
 
 Examples: 
-    paradigm PlaynodeName Shell 22 control.server.com
-    paradigm -u user -P 443 -l /var/lib/paradigm/log.paradigm PlaynodeName MPD 6600 control.server.com
+  paradigm PlaynodeName Shell 22 control.server.com
+  paradigm -u user -P 443 -l /var/lib/paradigm/log.paradigm PlaynodeName MPD 6600 control.server.com
 
 EOF
 }
@@ -45,21 +45,21 @@ EOF
 # Reset this POSIX variable in case getopts has been used previously in the shell.
 OPTIND=1
 while getopts "hl:u:P:" opt; do
-    case "$opt" in
-    h)
-        showHelp
-        exit 0
-        ;;
-    l)  
-        readonly LOGFILE="$OPTARG"
-        ;;
-    u)  
-        readonly CONTROLUSER="$OPTARG"
-        ;;
-    P)  
-        readonly SERVERLISTENINGPORT=$OPTARG
-        ;;
-    esac
+  case "$opt" in
+  h)
+    showHelp
+    exit 0
+    ;;
+  l)  
+    readonly LOGFILE="$OPTARG"
+    ;;
+  u)  
+    readonly CONTROLUSER="$OPTARG"
+    ;;
+  P)  
+    readonly SERVERLISTENINGPORT=$OPTARG
+    ;;
+  esac
 done
 shift $((OPTIND-1))
 [ "$1" = "--" ] && shift
@@ -79,35 +79,36 @@ if [ -z ${LOGFILE+x} ]; then readonly LOGFILE="$HOME/log.paradigm"; fi
 
 #==========# CALLED FROM END OF SCRIPT #==========#
 main() {
-    local pidFile=/tmp/paradigm-${SERVICENAME}.pid
-    if [ -f ${pidFile} ]; then
-        logEntry "II - Pid file found for ${SERVICENAME}"
-        local pid=$(cat ${pidFile})
-        if kill -0 $pid > /dev/null 2>&1; then
-            logEntry "II - Tunnel ${pid} found running (${SERVICENAME})."
-        else
-            logEntry "EE - Tunnel ${pid} not found in process list (${SERVICENAME})."
-            rm ${pidFile}
-            getPortalias ${SERVICENAME} ${pidFile}
-        fi
+  local pidFile=/tmp/paradigm-${SERVICENAME}.pid
+  if [ -f ${pidFile} ]; then
+    logEntry "II - Pid file found for ${SERVICENAME}"
+    local pid=$(cat ${pidFile})
+    if kill -0 $pid > /dev/null 2>&1; then
+      logEntry "II - Tunnel ${pid} found running (${SERVICENAME})."
     else
-        logEntry "WW - Pid file not found for ${SERVICENAME}."
-        getPortalias ${SERVICENAME} ${pidFile}
+      logEntry "EE - Tunnel ${pid} not found in process list (${SERVICENAME})."
+      rm ${pidFile}
+      getPortalias ${SERVICENAME} ${pidFile}
     fi
+  else
+      logEntry "WW - Pid file not found for ${SERVICENAME}."
+      portalias=$(getPortalias ${SERVICENAME} ${pidFile})
+      establishTunnel ${portalias} "${pidFile}"
+  fi
 }
 
 
 logEntry(){
-    echo "$(date) ${PLAYNODE} - ${1}" >> $LOGFILE
+  echo "$(date) ${PLAYNODE} - ${1}" >> $LOGFILE
 }
 
 
 getPortalias() {
-    local pidFile=$2
-    logEntry "II - getPortalias ${SERVICENAME}."
-    local portCmd="cat 'portalias-${SERVICENAME}' | grep '^${PLAYNODE}' | /usr/bin/cut -d^ -f2"
-    # Query remote server for remote ports to use for forwarding
-    local portalias=$(
+  local pidFile=$2
+  logEntry "II - getPortalias ${SERVICENAME}."
+  local portCmd="cat 'portalias-${SERVICENAME}' | grep '^${PLAYNODE}' | /usr/bin/cut -d^ -f2"
+  # Query remote server for remote ports to use for forwarding
+  local portalias=$(
     /usr/bin/ssh \
     -q \
     -p ${SERVERLISTENINGPORT} \
@@ -115,53 +116,53 @@ getPortalias() {
     -o ControlMaster=no \
     ${CONTROLUSER}@${CONTROLSERVER} \
     "${portCmd}" \
-    2>&1 )
-    # TODO: Below needs testing
-    if [ -z $portalias ]; then
-	logEntry "EE - Portalias not set. Connection failed or playnode not found."
-	exit 1
-    else
-	logEntry "II - Portalias is ${portalias}"
-	establishTunnel ${portalias} "${pidFile}"
-    fi
+  2>&1 )
+  # TODO: Below needs testing
+  if [ -z $portalias ]; then
+    logEntry "EE - Portalias not set. Connection failed or playnode not found."
+    exit 1
+  else
+    logEntry "II - Portalias is ${portalias}"
+    echo "${portalias}"
+  fi
 }
 
 
 establishTunnel() {
-    if [ $# -eq 2 ]; then
-        local portalias="$1"
-        local pidFile="$2"
-        logEntry "II - Portalias ${portalias} being used for local ${SERVICEPORT} ${pidFile}"
-    else
-        local portalias="NOTSET"
-        local pidFile="$1"
-        logEntry "EE - Number of args is wrong. getPortalias() failed. ${pidFile}"
-        # TODO Considering how serious an error this is, a failover should take effect.
-        return
-    fi
-    
-    # Forward $SERVICEPORT over remote $portalias, using $SERVERLISTENINGPORT outbound
-    /usr/bin/ssh \
-    -q \
-    -p ${SERVERLISTENINGPORT} \
-    -o StrictHostKeyChecking=no \
-    -o ServerAliveCountMax=2 \
-    -o ControlMaster=no \
-    -o ExitOnForwardFailure=yes \
-    -o TCPKeepAlive=yes \
-    -o ServerAliveInterval=45 \
-    -N \
-    -R ${portalias}:localhost:${SERVICEPORT} \
-    ${CONTROLUSER}@${CONTROLSERVER} & \
-    echo $! > "${pidFile}"
+  if [ $# -eq 2 ]; then
+      local portalias="$1"
+      local pidFile="$2"
+      logEntry "II - Portalias ${portalias} being used for local ${SERVICEPORT} ${pidFile}"
+  else
+      local portalias="NOTSET"
+      local pidFile="$1"
+      logEntry "EE - Number of args is wrong. getPortalias() failed. ${pidFile}"
+      # TODO Considering how serious an error this is, a failover should take effect.
+      return
+  fi
+  
+  # Forward $SERVICEPORT over remote $portalias, using $SERVERLISTENINGPORT outbound
+  /usr/bin/ssh \
+  -q \
+  -p ${SERVERLISTENINGPORT} \
+  -o StrictHostKeyChecking=no \
+  -o ServerAliveCountMax=2 \
+  -o ControlMaster=no \
+  -o ExitOnForwardFailure=yes \
+  -o TCPKeepAlive=yes \
+  -o ServerAliveInterval=45 \
+  -N \
+  -R ${portalias}:localhost:${SERVICEPORT} \
+  ${CONTROLUSER}@${CONTROLSERVER} & \
+  echo $! > "${pidFile}"
 }
 
 
 # This script requires at least 4 arguments to operate.
 # Display usage ifno if insufficient CLI args.
 if [ $# -lt 4 ]; then
-    showHelp
-    exit 1
+  showHelp
+  exit 1
 fi
 
 main # Call the main function once to start
